### 1. Tworzenie nowego projektu
POST http://localhost:8080/api/projects
Content-Type: application/json

{
  "name": "New Project2",
  "location": "New York"
}

### 2. Pobranie wszystkich projektów
GET http://localhost:8080/api/projects

### 3. Pobranie szczegółów projektu po ID
GET http://localhost:8080/api/projects/a0941ab7-2abd-4142-b94e-3aa8b0ff2361

### 4. Zaktualizowanie projektu
PUT http://localhost:8080/api/projects/a0941ab7-2abd-4142-b94e-3aa8b0ff2361
Content-Type: application/json

{
  "name": "Updated Project Text",
  "location": "New York"
}

### 5. Usunięcie projektu
DELETE http://localhost:8080/api/projects/a0941ab7-2abd-4142-b94e-3aa8b0ff2111


### 6. Tworzenie nowego materiału dla projektu
POST http://localhost:8080/api/materials/c43ed386-9114-40fe-b622-2cc9b2ea0bc0
Content-Type: application/json

{
  "name": "Example",
  "unit": "kg",
  "unitPrice": 100.0,
  "quantity": 50
}

### 7. Aktualizacja materiału
PUT http://localhost:8080/api/materials/c475024a-0f81-4711-8c27-12cf84cd5b15
Content-Type: application/json

{
  "name": "Updated Concrete",
  "unit": "kg",
  "unitPrice": 110.0,
  "quantity": 60
}

### 8. Pobranie szczegółów materiału
GET http://localhost:8080/api/materials/c475024a-0f81-4711-8c27-12cf84cd5b15

### 9. Usuwanie materiału
DELETE http://localhost:8080/api/materials/c475024a-0f81-4711-8c27-12cf84cd5b15

### 10. Pobranie wszystkich materiałów
GET http://localhost:8080/api/materials
