### 1. Tworzenie nowego projektu
POST http://localhost:8085/api/projects
Content-Type: application/json

{
  "name": "New Project2",
  "location": "New York"
}

### 2. Pobranie wszystkich projektów
GET http://localhost:8085/api/projects

### 3. Pobranie szczegółów projektu po ID
GET http://localhost:8085/api/projects/11111111-1111-1111-1111-111111111111

### 4. Zaktualizowanie projektu
PUT http://localhost:8085/api/projects/aadcf7ce-965a-42f2-936e-6d5cb4f27abc
Content-Type: application/json

{
  "name": "Updated Project Text",
  "location": "New York"
}

### 5. Usunięcie projektu
DELETE http://localhost:8085/api/projects/d070d0f0-d6c4-429c-a761-c2bce8099259


### 6. Tworzenie nowego materiału dla projektu
POST http://localhost:8085/api/materials/22222222-2222-2222-2222-222222222222
Content-Type: application/json

{
  "name": "Example",
  "unit": "kg",
  "unitPrice": 100.0,
  "quantity": 50
}

### 7. Aktualizacja materiału
PUT http://localhost:8085/api/materials/a3eeaa30-1697-44e9-a921-1c5ead46fcb8
Content-Type: application/json

{
  "name": "Updated Concrete",
  "unit": "kg",
  "unitPrice": 110.0,
  "quantity": 60
}

### 8. Pobranie szczegółów materiału
GET http://localhost:8085/api/materials/a3eeaa30-1697-44e9-a921-1c5ead46fcb8

### 9. Usuwanie materiału
DELETE http://localhost:8085/api/materials/e283f236-6104-4121-9fbd-858a42ac3521


### 10. Pobranie wszystkich materiałów
GET http://localhost:8085/api/materials