### 1. Tworzenie nowego projektu
POST http://localhost:8085/api/projects
Content-Type: application/json

{
  "name": "New Project1",
  "location": "New Yorkdsq"
}

### 2. Pobranie wszystkich projektów
GET http://localhost:8085/api/projects

### 3. Pobranie szczegółów projektu po ID
GET http://localhost:8085/api/projects/50d15bfe-347e-4a3f-87bb-c1491ca7c167

### 4. Zaktualizowanie projektu
PUT http://localhost:8085/api/projects/aadcf7ce-965a-42f2-936e-6d5cb4f27abc
Content-Type: application/json

{
  "name": "Updated Project Text",
  "location": "New York"
}

### 5. Usunięcie projektu
DELETE http://localhost:8085/api/projects/11111111-1111-1111-1111-111111111111


### 6. Tworzenie nowego materiału dla projektu
POST http://localhost:8085/api/materials/11111111-1111-1111-1111-111111111111
Content-Type: application/json

{
  "name": "test23",
  "unit": "kg",
  "unitPrice": 123456789.0,
  "quantity": 50
}

### 7. Aktualizacja materiału
PUT http://localhost:8085/api/materials/a3eeaa30-1697-44e9-a921-1c5ead46fcb8
Content-Type: application/json

{
  "name": "Updated Concrete",
  "unit": "kg",
  "unitPrice": 110.0,
  "quantity": 60
}

### 8. Pobranie szczegółów materiału
GET http://localhost:8085/api/materials/f23b0cba-e018-42b6-aa68-9f65ae99ef51

### 9. Usuwanie materiału
DELETE http://localhost:8085/api/materials/e283f236-6104-4121-9fbd-858a42ac3521


### 10. Pobranie wszystkich materiałów
GET http://localhost:8085/api/materials

### 11. Pobranie wszystkich materiałów dla projektu
GET http://localhost:8085/api/materials/project/ef9312ac-7448-4d68-b8f1-bb88eb026266